import type { Metadata } from 'next'
import Navbar from '@/components/navbar'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-jost">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
