export const HomeSlider2Data = [
  { label: 'Beds', imgUrl: '/bed-1.jpg', link: '#' },
  { label: 'Bookcases', imgUrl: '/book-1.jpg', link: '#' },
  { label: 'Coffee tables', imgUrl: '/coffee-1.jpg', link: '#' },
  { label: 'Dining tables', imgUrl: '/dining-1.jpg', link: '#' },
  { label: 'Chairs', imgUrl: '/chair-1.jpg', link: '#' },
  { label: 'Couches', imgUrl: '/couch-1.jpg', link: '#' },
  { label: 'Tables', imgUrl: '/table.jpg', link: '#' },
]

export const dummyProducts = [
  {
    brand: 'Brand',
    label: 'Good Comfy Couch',
    price: 120.0,
    stars: 3,
    imgUrl: '/sofa-green.jpg',
    hoverImgUrl: '/sofa-orange.jpg',
    oldPrice: 150.0,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Enim est facilis cupiditate labore, iusto magni autem officia unde vero. Facere ex consequatur animi eum, omnis obcaecati cum deleniti soluta velit ullam labore, iure laudantium eveniet laboriosam eos tempore! A, tempora.',
    quantity: 15,
    colors: ['#FFA500', '#008000', '#FF0000'],
    vendor: 'Good vendor',
    category: 'Couches',
    tags: ['Soft', 'Couches', 'Sofas', 'Sitting'],
  },
  {
    brand: 'Brand2',
    label: 'Good Wooden Chair',
    price: 67.0,
    stars: 5,
    imgUrl: '/chairr-1.jpg',
    hoverImgUrl: '/chairr-2.jpg',
    oldPrice: null,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Enim est facilis cupiditate labore, iusto magni autem officia unde vero. Facere ex consequatur animi eum, omnis obcaecati cum deleniti soluta velit ullam labore, iure laudantium eveniet laboriosam eos tempore! A, tempora.',
    quantity: 87,
    colors: ['#FFA500', '#008000', '#FF0000'],
    vendor: 'Heavy vendor',
    category: 'Chairs',
    tags: ['Wooden', 'Sitting', 'Study', 'Chair'],
  },
  {
    brand: 'Brand3',
    label: 'Comfy Bed with Pillows',
    price: 350.0,
    stars: 2,
    imgUrl: '/bedd-1.jpg',
    hoverImgUrl: '/bedd-2.jpg',
    oldPrice: 400,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Enim est facilis cupiditate labore, iusto magni autem officia unde vero. Facere ex consequatur animi eum, omnis obcaecati cum deleniti soluta velit ullam labore, iure laudantium eveniet laboriosam eos tempore! A, tempora.',
    quantity: 16,
    colors: ['#808080', '#964B00', '#FFC0CB'],
    vendor: 'Good Venor',
    category: 'Beds',
    tags: ['Wooden', 'Sitting', 'Study', 'Chair'],
  },
  {
    brand: 'Brand4',
    label: 'Dinning Table',
    price: 50,
    stars: 4,
    imgUrl: '/tablee-1.jpg',
    hoverImgUrl: '/tablee-2.jpg',
    oldPrice: 75,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Enim est facilis cupiditate labore, iusto magni autem officia unde vero. Facere ex consequatur animi eum, omnis obcaecati cum deleniti soluta velit ullam labore, iure laudantium eveniet laboriosam eos tempore! A, tempora.',
    quantity: 102,
    colors: ['#808080', '#964B00', '#FFC0CB'],
    vendor: 'Nice vendor',
    category: 'Tables',
    tags: ['Wooden', 'Sitting', 'Study', 'Chair'],
  },
  {
    brand: 'Brand4',
    label: 'Dinning Table for Family',
    price: 78,
    stars: 1,
    imgUrl: '/tablee-3.jpg',
    hoverImgUrl: '/tablee-4.jpg',
    oldPrice: 55,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Enim est facilis cupiditate labore, iusto magni autem officia unde vero. Facere ex consequatur animi eum, omnis obcaecati cum deleniti soluta velit ullam labore, iure laudantium eveniet laboriosam eos tempore! A, tempora.',
    quantity: 52,
    colors: ['#808080', '#964B00', '#FFC0CB'],
    vendor: 'Nice vendor',
    category: 'Tables',
    tags: ['Wooden', 'Sitting', 'Study', 'Chair'],
  },
  {
    brand: 'Brand',
    label: 'Good Comfy Couch',
    price: 120.0,
    stars: 3,
    imgUrl: '/sofa-green.jpg',
    hoverImgUrl: '/sofa-orange.jpg',
    oldPrice: 150.0,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Enim est facilis cupiditate labore, iusto magni autem officia unde vero. Facere ex consequatur animi eum, omnis obcaecati cum deleniti soluta velit ullam labore, iure laudantium eveniet laboriosam eos tempore! A, tempora.',
    quantity: 15,
    colors: ['#FFA500', '#008000', '#FF0000'],
    vendor: 'Good vendor',
    category: 'Couches',
    tags: ['Soft', 'Couches', 'Sofas', 'Sitting'],
  },
  {
    brand: 'Brand2',
    label: 'Good Wooden Chair',
    price: 67.0,
    stars: 5,
    imgUrl: '/chairr-1.jpg',
    hoverImgUrl: '/chairr-2.jpg',
    oldPrice: null,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Enim est facilis cupiditate labore, iusto magni autem officia unde vero. Facere ex consequatur animi eum, omnis obcaecati cum deleniti soluta velit ullam labore, iure laudantium eveniet laboriosam eos tempore! A, tempora.',
    quantity: 87,
    colors: ['#FFA500', '#008000', '#FF0000'],
    vendor: 'Heavy vendor',
    category: 'Chairs',
    tags: ['Wooden', 'Sitting', 'Study', 'Chair'],
  },
  {
    brand: 'Brand3',
    label: 'Comfy Bed with Pillows',
    price: 350.0,
    stars: 2,
    imgUrl: '/bedd-1.jpg',
    hoverImgUrl: '/bedd-2.jpg',
    oldPrice: 400,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Enim est facilis cupiditate labore, iusto magni autem officia unde vero. Facere ex consequatur animi eum, omnis obcaecati cum deleniti soluta velit ullam labore, iure laudantium eveniet laboriosam eos tempore! A, tempora.',
    quantity: 16,
    colors: ['#808080', '#964B00', '#FFC0CB'],
    vendor: 'Good Venor',
    category: 'Beds',
    tags: ['Wooden', 'Sitting', 'Study', 'Chair'],
  },
]
